stages:
    - build
build_project:
    stage: build
    script:
        - xcodebuild clean -project InMotion/InMotion.xcodeproj -scheme InMotion
        - xcodebuild test -project InMotion/InMotion.xcodeproj -scheme InMotion -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.0'
