stages:
    - build
build_project:
    stage: build
    script:
        - xcodebuild clean -project InMotion.xcodeproj -scheme InMotion
        - xcodebuild test -project InMotion.xcodeproj -scheme InMotion -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.7'
